/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { MerkleTreeBranchDTO } from './MerkleTreeBranchDTO.js';
import {
    MerkleTreeBranchDTOFromJSON,
    MerkleTreeBranchDTOFromJSONTyped,
    MerkleTreeBranchDTOToJSON,
} from './MerkleTreeBranchDTO.js';
import type { MerkleTreeBranchLinkDTO } from './MerkleTreeBranchLinkDTO.js';
import {
    MerkleTreeBranchLinkDTOFromJSON,
    MerkleTreeBranchLinkDTOFromJSONTyped,
    MerkleTreeBranchLinkDTOToJSON,
} from './MerkleTreeBranchLinkDTO.js';
import type { MerkleTreeLeafDTO } from './MerkleTreeLeafDTO.js';
import {
    MerkleTreeLeafDTOFromJSON,
    MerkleTreeLeafDTOFromJSONTyped,
    MerkleTreeLeafDTOToJSON,
} from './MerkleTreeLeafDTO.js';
import type { MerkleTreeNodeTypeEnum } from './MerkleTreeNodeTypeEnum.js';
import {
    MerkleTreeNodeTypeEnumFromJSON,
    MerkleTreeNodeTypeEnumFromJSONTyped,
    MerkleTreeNodeTypeEnumToJSON,
} from './MerkleTreeNodeTypeEnum.js';

/**
 * 
 * @export
 * @interface MerkleStateInfoDTOTreeInner
 */
export interface MerkleStateInfoDTOTreeInner {
    /**
     * 
     * @type {MerkleTreeNodeTypeEnum}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    type: MerkleTreeNodeTypeEnum;
    /**
     * Leaf path.
     * @type {string}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    path: string;
    /**
     * Encoded leaf path.
     * @type {string}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    encodedPath: string;
    /**
     * Nibble count.
     * @type {number}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    nibbleCount: number;
    /**
     * Branch link bitmask.
     * @type {string}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    linkMask: string;
    /**
     * Branch links (max 16).
     * @type {Array<MerkleTreeBranchLinkDTO>}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    links: Array<MerkleTreeBranchLinkDTO>;
    /**
     * 
     * @type {string}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    branchHash: string;
    /**
     * Leaf value (sha256 hash).
     * @type {string}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof MerkleStateInfoDTOTreeInner
     */
    leafHash: string;
}

/**
 * Check if a given object implements the MerkleStateInfoDTOTreeInner interface.
 */
export function instanceOfMerkleStateInfoDTOTreeInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "encodedPath" in value;
    isInstance = isInstance && "nibbleCount" in value;
    isInstance = isInstance && "linkMask" in value;
    isInstance = isInstance && "links" in value;
    isInstance = isInstance && "branchHash" in value;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "leafHash" in value;

    return isInstance;
}

export function MerkleStateInfoDTOTreeInnerFromJSON(json: any): MerkleStateInfoDTOTreeInner {
    return MerkleStateInfoDTOTreeInnerFromJSONTyped(json, false);
}

export function MerkleStateInfoDTOTreeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerkleStateInfoDTOTreeInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': MerkleTreeNodeTypeEnumFromJSON(json['type']),
        'path': json['path'],
        'encodedPath': json['encodedPath'],
        'nibbleCount': json['nibbleCount'],
        'linkMask': json['linkMask'],
        'links': ((json['links'] as Array<any>).map(MerkleTreeBranchLinkDTOFromJSON)),
        'branchHash': json['branchHash'],
        'value': json['value'],
        'leafHash': json['leafHash'],
    };
}

export function MerkleStateInfoDTOTreeInnerToJSON(value?: MerkleStateInfoDTOTreeInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': MerkleTreeNodeTypeEnumToJSON(value.type),
        'path': value.path,
        'encodedPath': value.encodedPath,
        'nibbleCount': value.nibbleCount,
        'linkMask': value.linkMask,
        'links': ((value.links as Array<any>).map(MerkleTreeBranchLinkDTOToJSON)),
        'branchHash': value.branchHash,
        'value': value.value,
        'leafHash': value.leafHash,
    };
}

