export const STORAGE_KEYS = {
  secure: {
    ACCOUNT: 'ACCOUNT_SERVICE',
    MNEMONIC: 'MNEMONIC_SERVICE',
    PRIVATEKEY: 'PRIVATEKEY_SERIVCE',
  },
  async: {
    ACCOUNT: 'ACCOUNT_SERVICE',
    WALLET: 'WALLET_SERVICE',
    NETWORK: 'NETWORK_SERVICE',
    NODESTATISTICS: 'NODESTATISTICS_SERVICE',
    LANGUAGE: 'LANGUAGE_SERVICE',
    CONTACT: 'CONTACT_SERVICE',
    NOTIFICATION: 'NOTIFICATION_SERVICE',
  },
};
